services:

  app:
    image: diegomrs/agenda:1.0.0

    deploy:
      replicas: 2

    ports:
      - "5000:5000"

    environment:
      DATABASE_URL: postgresql://postgres:admin1234@db:5432/examen_u3

    networks:
      - examen_dhg

networks:
  examen_dhg:
    external: true